version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Cshop
      POSTGRES_PASSWORD: cspass
      POSTGRES_DB: cottageshop


  web:
    image: apantslessman/cottageshop:latest
    ports:
      - "8080:8000"  # Maps port 8000 on the host to port 8000 in the container
    volumes:
      - csimg:/app/build/assets
    environment:
      POSTGRES_USER: Cshop
      POSTGRES_PASSWORD: cspass
      POSTGRES_DB: cottageshop
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db


volumes:
  pgdata:
  csimg: