name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Build React app
      run: cd frontend && npm run build

    - name: Remove existing build directory in Flask app
      run: rm -rf ./backend/build  # Ensure this path matches your Flask app directory

    - name: Move build to Flask app directory
      run: mv ./frontend/build ./backend/build  # Replace with your Flask app directory
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: backend
        file: backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cottageshop:latest

